sudo: required

language: python

services:
  - docker

before_install:
  - if [[ "${TRAVIS_TAG}x" == "x" ]] ; then ./set-version.sh $(tail -1 .versions)-snapshot; ./spec/examples/inject-manifests.sh; fi
  - mkdir -p output
  - docker pull rochdev/alpine-asciidoctor:mini
  - pip install json-spec

script:
  - ./spec/examples/validate-examples.sh
  - ./spec/add-version-links.sh
  - docker run -v $TRAVIS_BUILD_DIR/spec:/documents --name asciidoc-to-html rochdev/alpine-asciidoctor:mini asciidoctor -D /documents/output index.adoc seed.adoc
  - docker run -v $TRAVIS_BUILD_DIR/spec:/documents --name asciidoc-to-pdf rochdev/alpine-asciidoctor:mini asciidoctor-pdf -D /documents/output seed.adoc
  # - docker run -v $TRAVIS_BUILD_DIR/spec:/documents --name asciidoc-to-manpage rochdev/alpine-asciidoctor:mini asciidoctor-manpage -b manpage -D /documents/output seed.man.adoc

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  # - docker logs asciidoc-to-manpage

before_deploy:
  - ./spec/collect-versioned-docs.sh

deploy:
  # Deployment that pushes GitHub releases of compiled spec docs associated with tag
  - provider: releases
    api_key: "$GH_TOKEN"
    file_glob: true
    file: spec/output/${TRAVIS_TAG}/*
    skip_cleanup: true
    on:
      tags: true

  # Only performed on master builds. For releases, timing of master build must be after artifacts are available.
  - provider: pages
    local_dir: spec/output
    skip_cleanup: true
    github_token: $GH_TOKEN
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST == false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/10070a680400c55e3baa
    on_success: change
    on_failure: always
    on_start: never